export const ROUTES = {
  ROOT: '/',
  ABOUT: '/about',
  PRODUCTS: '/products',
  LOGIN: '/login',
  SIGNUP: '/signup',
  FOOD: '/food',
  TREATS: '/treats',
  TOYS: '/toys',
  BEDDINGS_FURNITURE: '/beddings_furniture',
  GROOMING: '/grooming_products',
  HEALTH: '/health',
  PRODUCT: '/product',
  CLOTHING: '/clothing',
  FEEDING: '/feeding_watering',
  ORDER: '/order',
  USER_SETTINGS: '/account-settings',
  USER_ORDERS: '/my-orders',
  ORDERS: '/orders',
  ADD_PRODUCT: '/add-product',
  EDIT_RODUCT: '/edit-product',
  DASHBOARD: '/dashboard'
}